package com.engabd.sendpin.protocol.noise

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * CPACE-X25519-SHA512 and the PIN-pairing derivations against the reference libraries
 * (the `cpace` package and aiosendspin 9.1.1's `pin` / `pairing` modules), with both
 * scalars fixed. Generated by scratch `gen_cpace_vectors.py`.
 */
class CPaceTest {
    private val h = "99da36a333fe09ceec635b347a83e03af2bb964994ca6cbe5e36372b5ac17a56".hex()
    private val sid = PinPairing.sid(h, 1)
    private val pin = "123456"
    private val serverScalar = "0a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20212223242526272829".hex()
    private val clientScalar = "464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465".hex()

    @Test
    fun `session id is the spec's label, hash and counter`() {
        assertEquals("73656e647370696e2d706169722d70616b652d763199da36a333fe09ceec635b347a83e03af2bb964994ca6cbe5e36372b5ac17a5600000001", sid.toHex())
    }

    @Test
    fun `generator and shares match the reference`() {
        assertEquals("2291595501a00121f50d69dd07ef7ebeeba6ca285236e3b903d8286d7e606029", CPace.calculateGenerator(pin.toByteArray(), ByteArray(0), sid).toHex())
        val b = CPace.start(CPace.Role.RESPONDER, pin.toByteArray(), sid, ad = PinPairing.AD_CLIENT, scalar = clientScalar)
        assertEquals("eb847be76aa41c0d5f77adc02b74b4eade769474e12b66f96523e97fb1070e76", b.publicShare.toHex(), "Yb")
        val a = CPace.start(CPace.Role.INITIATOR, pin.toByteArray(), sid, ad = PinPairing.AD_SERVER, scalar = serverScalar)
        assertEquals("9952690b9505837d1830ba09c50364b814489235be1e7ba3b0b8690b5bbb9125", a.publicShare.toHex(), "Ya")
    }

    @Test
    fun `both sides derive the reference ISK and confirmation tags`() {
        val a = CPace.start(CPace.Role.INITIATOR, pin.toByteArray(), sid, ad = PinPairing.AD_SERVER, scalar = serverScalar)
        val b = CPace.start(CPace.Role.RESPONDER, pin.toByteArray(), sid, ad = PinPairing.AD_CLIENT, scalar = clientScalar)
        a.derive(b.publicShare, PinPairing.AD_CLIENT)
        b.derive(a.publicShare, PinPairing.AD_SERVER)
        assertEquals("1bcba0f65a8b96a85758a8dd90a69428667db0664aace1c7304c682b14ce34cfd4883c85282bcd73eda98446da7b074b27bbb690b1ea5cc3284c7411ac083814", b.isk.toHex(), "ISK")
        assertEquals("d3bf0894e8d38c52327f384641e47c1e824c1ac534c9a5a31fed001d03060958c38d6dbae80b003262a75dbf22c63010e0fe15b5aa65ff965eceea93e53fc6fe", a.tag().toHex(), "Ta")
        assertEquals("276b545773855030d347ee81b1e2e36968551d474191ca3bc573ab9e43ed4b79c7a5fdacc62f828abc8962d62b2298b2937a45ad89395155fc4a8fab61315dd6", b.tag().toHex(), "Tb")
        assertTrue(b.verify(a.tag()))
        assertTrue(a.verify(b.tag()))
        assertFalse(b.verify(b.tag()), "own tag is not the peer's")
    }

    @Test
    fun `a wrong PIN fails confirmation without a protocol error`() {
        val a = CPace.start(CPace.Role.INITIATOR, "654321".toByteArray(), sid, ad = PinPairing.AD_SERVER, scalar = serverScalar)
        val b = CPace.start(CPace.Role.RESPONDER, pin.toByteArray(), sid, ad = PinPairing.AD_CLIENT, scalar = clientScalar)
        a.derive(b.publicShare, PinPairing.AD_CLIENT)
        b.derive(a.publicShare, PinPairing.AD_SERVER)
        assertFalse(b.verify(a.tag()))
    }

    @Test
    fun `dynamic PIN, commitment and PSK wrapping match the reference`() {
        val nonceA = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20".hex()
        val nonceB = "65666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f8081828384".hex()
        assertEquals("502538", PinPairing.derivePin(h, nonceA, nonceB, 6))
        assertEquals("f10407bb189d39d4d6dbbe6fcb2e0e03e318c6e91b9224088384ce4ce04067c0", PinPairing.commit(nonceB).toHex())
        val b = CPace.start(CPace.Role.RESPONDER, pin.toByteArray(), sid, ad = PinPairing.AD_CLIENT, scalar = clientScalar)
        b.derive("9952690b9505837d1830ba09c50364b814489235be1e7ba3b0b8690b5bbb9125".hex(), PinPairing.AD_SERVER)
        val wk = PinPairing.wrapKey(sid, b.isk)
        assertEquals("5076c7108709c73c6dda60699a8068553fc4ff2cc4dc5575a7baf332cb1fd25d", wk.toHex(), "K_wrap")
        assertEquals("3d886d5579aba58df5fe9e62321f65d1fc08f981ca136e7ab358128d666f30d3f29fe92f39a7d07c18846ee037b9f449", PinPairing.wrapPsk(NoiseCipherSuite.AESGCM, wk, "c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7".hex()).toHex(), "wrapped_psk")
        assertEquals(48, PinPairing.wrapPsk(NoiseCipherSuite.AESGCM, wk, ByteArray(32)).size)
    }
}
