package com.engabd.sendpin.protocol.noise

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

/**
 * The Noise `KKpsk2` responder against a transcript recorded from the reference
 * implementation (the `noiseprotocol` library that aiosendspin's server uses), with both
 * sides' static and ephemeral keys fixed. If the Kotlin side reproduces message 2, the
 * handshake hash and both transport directions byte for byte, it will interoperate with
 * Music Assistant; a single wrong `MixHash` shows up as a tag failure on the first frame.
 */
class NoiseHandshakeTest {

    class Vector(
        val serverStatic: String, val clientStatic: String,
        val serverEphemeral: String, val clientEphemeral: String,
        val serverPub: String, val clientPub: String,
        val psk: String, val prologue: String, val payload1: String,
        val msg1: String, val msg2: String, val handshakeHash: String,
        val ctServer1: String, val ctServer2: String, val ctClient1: String,
    )

    companion object {
        // Generated by scratch `gen_vectors.py` with noiseprotocol 0.3.1.
        val AESGCM = Vector(
            serverStatic = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
            clientStatic = "65666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f8081828384",
            serverEphemeral = "c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8",
            clientEphemeral = "333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152",
            serverPub = "07a37cbc142093c8b755dc1b10e86cb426374ad16aa853ed0bdfc0b2b86d1c7c",
            clientPub = "5714769d116bf76436ae74bc793d2c30ad1903c59ac5273805c7e2698b410c36",
            psk = "1b5e24dbc1aed95fc2a5a338a90c05df44bd10f5ec1f4cd66cbf86272767b9d3",
            prologue = "7b2274797065223a22636c69656e742f696e6974222c227061796c6f6164223a7b22636c69656e745f6964223a2278222c2276657273696f6e223a312c227375697465223a2232353531395f41455347434d5f534841323536227d7d7b2274797065223a227365727665722f696e6974222c227061796c6f6164223a7b227365727665725f6964223a2279222c2276657273696f6e223a317d7d",
            payload1 = "7b2270736b5f6964223a224746735639744c6153516d3948634657704b736759514f7237774654764e55746b6d467775567a337a6f6f227d",
            msg1 = "4c29f4996985e80d247e80b70303824592ff9fbad74904ea7c3d2bda24e51c122c1d4123e0f2faa043f5c6151a663dca23b333ef579f4ffc16096de16bdb643d6f1bbd14a6b819a0c49b0373ad1f4bade8c5c693da599def8668d7e9ec81231fc0704df290c5e8ad",
            msg2 = "c15d2265459455c9ff156e6c1da6bfb7910bb8af50f2b2f9f853ea9325259d4de6f8560445ef733b63213608933a22fc18d5",
            handshakeHash = "cdf960c6a2527dfe455329afa98e83b315b0b8858105bf3ac843126097adeaff",
            ctServer1 = "8deee5443be847625704b2c07bbdefb16b6e12ca490f5aa779fd3bb2ae8984007ef3",
            ctServer2 = "c84ad0717e65a889b15faade9d186a3687d490a742da37",
            ctClient1 = "56baca1807cdaa720c45e8de80d6fffa295c2436789fa1106cdb016e62d20ee11bc7",
        )
        val CHACHAPOLY = Vector(
            serverStatic = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
            clientStatic = "65666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f8081828384",
            serverEphemeral = "c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8",
            clientEphemeral = "333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152",
            serverPub = "07a37cbc142093c8b755dc1b10e86cb426374ad16aa853ed0bdfc0b2b86d1c7c",
            clientPub = "5714769d116bf76436ae74bc793d2c30ad1903c59ac5273805c7e2698b410c36",
            psk = "1b5e24dbc1aed95fc2a5a338a90c05df44bd10f5ec1f4cd66cbf86272767b9d3",
            prologue = "7b2274797065223a22636c69656e742f696e6974222c227061796c6f6164223a7b22636c69656e745f6964223a2278222c2276657273696f6e223a312c227375697465223a2232353531395f436861436861506f6c795f534841323536227d7d7b2274797065223a227365727665722f696e6974222c227061796c6f6164223a7b227365727665725f6964223a2279222c2276657273696f6e223a317d7d",
            payload1 = "7b2270736b5f6964223a224746735639744c6153516d3948634657704b736759514f7237774654764e55746b6d467775567a337a6f6f227d",
            msg1 = "4c29f4996985e80d247e80b70303824592ff9fbad74904ea7c3d2bda24e51c1220457795e4303d7fcd124f73be5db18ef4f4ea5494dddad8701d8c47b0d057670982d82657a926d01ab38b3b72789a91ccd116787255899a18355b64055ba74a9ffa60fe631be17b",
            msg2 = "c15d2265459455c9ff156e6c1da6bfb7910bb8af50f2b2f9f853ea9325259d4dacc949551cfbfb8ee66eb7acbe32a3736f4a",
            handshakeHash = "af487cca0431f0554acc48206e18783dbe9c1eb5415440ddf48caa556cbceb0c",
            ctServer1 = "43e4822208faa1bcd76fb6f2becdc68a1fe304b80bdbd874207e2d86e6b4843395c7",
            ctServer2 = "9f73e5a991bad04339829071a81d4d7e59c42fa5a27eb1",
            ctClient1 = "71ca727661da1e2dd3b1337b2e7360382d713491566b293fbe603dfabc5b850cb492",
        )
    }

    private fun run(suite: NoiseCipherSuite, v: Vector) {
        assertEquals(v.clientPub, X25519.publicKey(v.clientStatic.hex()).toHex(), "client static pub")
        assertEquals(v.serverPub, X25519.publicKey(v.serverStatic.hex()).toHex(), "server static pub")

        val hs = NoiseHandshake(
            suite = suite,
            localStaticPrivate = v.clientStatic.hex(),
            remoteStaticPublic = v.serverPub.hex(),
            prologue = v.prologue.hex(),
            ephemeralPrivate = v.clientEphemeral.hex(),
        )
        val payload1 = hs.readMessage1(v.msg1.hex())
        assertEquals(v.payload1, payload1.toHex(), "message 1 payload")

        val (msg2, result) = hs.writeMessage2(v.psk.hex(), "{}".toByteArray())
        assertEquals(v.msg2, msg2.toHex(), "message 2")
        assertEquals(v.handshakeHash, result.handshakeHash.toHex(), "handshake hash")

        // Transport: the server's frames decrypt in order, ours match its expectation.
        val t = result.transport
        assertContentEquals(byteArrayOf(0) + "hello from server".toByteArray(), t.decrypt(v.ctServer1.hex()))
        assertContentEquals(byteArrayOf(4) + "second".toByteArray(), t.decrypt(v.ctServer2.hex()))
        assertEquals(v.ctClient1, t.encrypt(byteArrayOf(0) + "hello from client".toByteArray()).toHex(), "client transport")
    }

    @Test
    fun `AESGCM transcript matches the reference`() = run(NoiseCipherSuite.AESGCM, AESGCM)

    @Test
    fun `ChaChaPoly transcript matches the reference`() = run(NoiseCipherSuite.CHACHAPOLY, CHACHAPOLY)

    @Test
    fun `a replayed transport frame fails authentication`() {
        val v = AESGCM
        val hs = NoiseHandshake(NoiseCipherSuite.AESGCM, v.clientStatic.hex(), v.serverPub.hex(), v.prologue.hex(), v.clientEphemeral.hex())
        hs.readMessage1(v.msg1.hex())
        val (_, result) = hs.writeMessage2(v.psk.hex(), "{}".toByteArray())
        result.transport.decrypt(v.ctServer1.hex())
        // The counter moved on; the same bytes again are a replay.
        assertFailsWith<javax.crypto.AEADBadTagException> { result.transport.decrypt(v.ctServer1.hex()) }
    }

    @Test
    fun `a tampered message 1 is a handshake failure`() {
        val v = AESGCM
        val hs = NoiseHandshake(NoiseCipherSuite.AESGCM, v.clientStatic.hex(), v.serverPub.hex(), v.prologue.hex(), v.clientEphemeral.hex())
        val bad = v.msg1.hex().also { it[it.size - 1] = (it[it.size - 1].toInt() xor 1).toByte() }
        assertFailsWith<NoiseHandshakeException> { hs.readMessage1(bad) }
    }

    @Test
    fun `the wrong prologue is a handshake failure`() {
        val v = AESGCM
        val hs = NoiseHandshake(NoiseCipherSuite.AESGCM, v.clientStatic.hex(), v.serverPub.hex(), "different".toByteArray(), v.clientEphemeral.hex())
        assertFailsWith<NoiseHandshakeException> { hs.readMessage1(v.msg1.hex()) }
    }
}

internal fun String.hex(): ByteArray = chunked(2).map { it.toInt(16).toByte() }.toByteArray()
internal fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
