package com.engabd.sendpin.audio

import androidx.annotation.OptIn
import androidx.media3.common.C
import androidx.media3.common.audio.AudioProcessor
import androidx.media3.common.audio.BaseAudioProcessor
import androidx.media3.common.util.UnstableApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.tanh

/**
 * Lo-fi music mode: high-pass, bitcrusher, warm saturation, low-pass, and
 * an optional noise texture, all behind one intensity slider.
 *
 * At 0, the processor is transparent. At 1, it is full lo-fi hip-hop:
 * trimmed of sub-bass, downsampled, quantised, warm, and rolled off. The
 * whole chain is one [BaseAudioProcessor] so it can be a single entry in the
 * sink's processor chain alongside [LocalDsp] and [AudioAnalysisTap].
 *
 * Per-sample order, in [processSample]: high-pass (trims sub-bass before it
 * can waste quantisation steps) → decimation → bit-depth reduction →
 * saturation → low-pass (rolls off the harshness the bitcrusher/saturation
 * added) → this processor's own noise texture, added last so it is never
 * quantised or decimated along with the music — see [TapRenderersFactory]'s
 * class doc for why that ordering matters.
 *
 * The noise texture (crackle plus a light hiss floor) is generated by a
 * private [VinylNoiseEngine] instance — the same mechanics
 * [VinylNoiseProcessor] uses, just at quieter curves ([loFiCrackleAmplitude],
 * [loFiHissAmplitude]): a light dusting, not the main event. When vinyl noise
 * ([VinylNoiseProcessor]) is also in the chain and enabled, this processor
 * skips its own noise texture and lets the dedicated processor handle it,
 * avoiding two independent noise generators on the same signal. The caller
 * sets [Config.shareVinylCrackle] to true when both are active.
 *
 * Sits ahead of [VinylNoiseProcessor] and [OldRadioProcessor], before
 * [AudioAnalysisTap], in the chain — see [TapRenderersFactory].
 *
 * Threading follows the same contract as [LocalDsp]: [queueInput] runs on
 * the audio thread, [setConfig] is safe from any thread, and the active
 * config is read from a `@Volatile` snapshot at the top of a buffer.
 */
@OptIn(UnstableApi::class)
class LoFiProcessor : BaseAudioProcessor() {

    @Serializable
    data class Config(
        val enabled: Boolean = false,
        /** 0..1. Maps to bit depth, decimation, saturation drive, and high-pass/low-pass cutoffs. */
        val intensity: Float = 0.5f,
        /** True when [VinylNoiseProcessor] is also active, so noise texture is shared. */
        val shareVinylCrackle: Boolean = false,
    ) {
        fun isActive(): Boolean = enabled && intensity > 0f
    }

    @Volatile
    private var pending: Config? = Config()

    private var active: Config = Config()
    private var channelCount = 2
    private var sampleRate = 44_100
    private var encoding = C.ENCODING_PCM_16BIT

    // --- Decimation state: hold-and-sample ---
    /**
     * How many consecutive samples to hold before advancing. 1 = transparent,
     * 4 = strong downsampling aliasing. Maps from intensity.
     */
    private var decimate = 1
    private var decimateCounter = 0
    private var heldSample = FloatArray(2)

    // --- High-pass/low-pass: one Biquad section each, per channel ---
    private class ChannelFilters {
        val highPass = Biquad()
        val lowPass = Biquad()
    }

    private var filters: Array<ChannelFilters> = Array(2) { ChannelFilters() }

    /** This processor's own noise texture (only used when not sharing with [VinylNoiseProcessor]). */
    private val noise = VinylNoiseEngine()

    fun setConfig(config: Config) {
        pending = config
    }

    /** The config the current coefficients were built from. For the sharing logic. */
    fun currentConfigSafe(): Config = active

    companion object {
        private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }

        fun encode(config: Config): String = json.encodeToString(Config.serializer(), config)
        fun decode(raw: String): Config? =
            runCatching { json.decodeFromString(Config.serializer(), raw) }.getOrNull()

        /**
         * Bit depth from intensity: 16 bits (transparent) down to 6 bits (crushed).
         *
         * The mapping is linear in the lower half and steeper in the upper half,
         * so gentle settings stay clean and aggressive settings crush hard.
         */
        internal fun bitDepth(intensity: Float): Int {
            // 0.0 -> 16, 0.5 -> 12, 1.0 -> 6
            val i = intensity.coerceIn(0f, 1f)
            return when {
                i < 0.01f -> 16
                i <= 0.5f -> (16 - (i * 8f)).toInt()  // 16 down to 12
                else -> (12 - ((i - 0.5f) * 12f)).toInt()  // 12 down to 6
            }.coerceIn(6, 16)
        }

        /**
         * Quantisation levels from bit depth: 2^bits - 1, centred at zero.
         */
        internal fun quantise(x: Float, bits: Int): Float {
            if (bits >= 16) return x
            val levels = (1 shl bits) - 1
            return (Math.round(x * levels).toFloat() / levels).coerceIn(-1f, 1f)
        }

        /**
         * Decimation factor from intensity: 1 (transparent) to 4 (strong).
         */
        internal fun decimationFactor(intensity: Float): Int {
            val i = intensity.coerceIn(0f, 1f)
            return when {
                i < 0.01f -> 1
                i < 0.33f -> 2
                i < 0.66f -> 3
                else -> 4
            }
        }

        /**
         * Saturation drive from intensity: 1.0 (transparent) to 3.0 (heavy).
         *
         * The tanh soft clipper is `tanh(drive * x) / tanh(drive)`, which
         * normalises so unity input maps to unity output at any drive.
         * At drive 1 it is nearly linear; at drive 3 it is clearly saturating.
         */
        internal fun saturationDrive(intensity: Float): Float {
            val i = intensity.coerceIn(0f, 1f)
            return 1f + i * 2f  // 1.0 to 3.0
        }

        internal fun saturate(x: Float, drive: Float): Float {
            if (drive <= 1.01f) return x
            val d = tanh(drive.toDouble())
            return (tanh(drive * x.toDouble()) / d).toFloat()
        }

        /**
         * Low-pass corner from intensity: 20 kHz (inaudible) down to 3 kHz at
         * full intensity — the same curve the old one-pole filter used, now
         * feeding a 2-pole [Biquad] instead. The steeper 12 dB/octave slope
         * reads as a far more convincing "muffled speaker" at the same
         * corner frequency than the old 6 dB/octave tilt did.
         */
        internal fun lowPassFreqHz(intensity: Float): Float {
            val i = intensity.coerceIn(0f, 1f)
            return if (i < 0.01f) 20_000f else 20_000f - i * 17_000f
        }

        /**
         * High-pass corner from intensity: bypassed (0, meaning "no
         * filtering") at zero intensity, up to 140 Hz at full intensity.
         *
         * Trims club-style sub-bass so a rounder, punchier mid-bass has
         * room — the classic lo-fi hip-hop EQ move this processor was
         * missing entirely; [lowPassFreqHz] above only ever attenuates highs.
         */
        internal fun highPassFreq(intensity: Float): Float {
            val i = intensity.coerceIn(0f, 1f)
            return if (i < 0.01f) 0f else 60f + i * 80f  // 60 Hz .. 140 Hz
        }

        /**
         * Crackle amplitude for this processor's own noise texture (when
         * vinyl noise is not sharing). Quieter than the dedicated processor:
         * lo-fi crackle is a light dusting, not the main event.
         */
        internal fun loFiCrackleAmplitude(intensity: Float): Float = (intensity * 0.06f).coerceIn(0f, 0.06f)

        /**
         * Hiss floor for this processor's own noise texture (when vinyl
         * noise is not sharing). Quieter than the dedicated Vinyl mode's
         * hiss — the same "light dusting" relationship [loFiCrackleAmplitude]
         * already has to [VinylNoiseProcessor.crackleAmplitude].
         */
        internal fun loFiHissAmplitude(intensity: Float): Float =
            VinylNoiseProcessor.hissAmplitude(intensity) * 0.5f
    }

    /** Rebuilds the high-pass/low-pass coefficients for the live intensity and sample rate. */
    private fun updateFilterCoefficients() {
        val hp = highPassFreq(active.intensity)
        val lp = lowPassFreqHz(active.intensity)
        for (f in filters) {
            if (hp <= 0f) f.highPass.setPassthrough() else f.highPass.setHighPass(sampleRate, hp, q = 0.707f)
            f.lowPass.setLowPass(sampleRate, lp, q = 0.707f)
        }
    }

    override fun onConfigure(
        inputAudioFormat: AudioProcessor.AudioFormat,
    ): AudioProcessor.AudioFormat = when (inputAudioFormat.encoding) {
        C.ENCODING_PCM_16BIT, C.ENCODING_PCM_FLOAT -> {
            sampleRate = inputAudioFormat.sampleRate
            channelCount = inputAudioFormat.channelCount
            encoding = inputAudioFormat.encoding
            if (channelCount > heldSample.size) {
                heldSample = FloatArray(channelCount)
                filters = Array(channelCount) { ChannelFilters() }
            }
            noise.resize(channelCount)
            noise.configureFilters(sampleRate)
            updateFilterCoefficients()
            pending = active
            inputAudioFormat
        }
        else -> AudioProcessor.AudioFormat.NOT_SET
    }

    override fun queueInput(inputBuffer: ByteBuffer) {
        pending?.let {
            active = it
            decimate = decimationFactor(it.intensity)
            updateFilterCoefficients()
            noise.resetCrackleThreshold(VinylNoiseProcessor.crackleInterval(it.intensity, sampleRate))
            pending = null
        }

        val remaining = inputBuffer.remaining()
        if (remaining == 0) return

        val order = inputBuffer.order()
        val out = replaceOutputBuffer(remaining)
        // The output buffer comes back in native order; the bytes copied into it
        // are the input's. Carrying the input's order across means a pass-through
        // reads back as the same samples, not as byte-swapped ones — the active
        // paths below already do this, and the two disagreeing is what a
        // big-endian caller would see as silent corruption.
        out.order(order)
        if (!active.isActive()) {
            out.put(inputBuffer).flip()
            return
        }

        when (encoding) {
            C.ENCODING_PCM_FLOAT -> processFloat(inputBuffer, out, order)
            else -> processShort(inputBuffer, out, order)
        }
        out.flip()
    }

    private fun processFloat(input: ByteBuffer, out: ByteBuffer, order: ByteOrder) {
        out.order(order)
        var channel = 0
        val bits = bitDepth(active.intensity)
        val drive = saturationDrive(active.intensity)
        val addNoise = active.isActive() && !active.shareVinylCrackle

        while (input.hasRemaining()) {
            if (channel == 0 && addNoise) noise.advanceFrame(sampleRate)
            val x = input.float
            val y = processSample(x, channel, bits, drive, addNoise)
            out.putFloat(y.coerceIn(-1f, 1f))
            channel = (channel + 1) % channelCount
        }
    }

    private fun processShort(input: ByteBuffer, out: ByteBuffer, order: ByteOrder) {
        out.order(order)
        var channel = 0
        val bits = bitDepth(active.intensity)
        val drive = saturationDrive(active.intensity)
        val addNoise = active.isActive() && !active.shareVinylCrackle

        while (input.remaining() >= 2) {
            if (channel == 0 && addNoise) noise.advanceFrame(sampleRate)
            val x = input.short / 32_768f
            val y = processSample(x, channel, bits, drive, addNoise)
            val clamped = (y.coerceIn(-1f, 1f) * 32_767f)
            out.putShort(clamped.toInt().toShort())
            channel = (channel + 1) % channelCount
        }
        while (input.hasRemaining()) out.put(input.get())
    }

    /**
     * One sample through the lo-fi chain: high-pass, decimate, quantise,
     * saturate, low-pass, then (last, unquantised) this processor's own
     * noise texture.
     */
    private fun processSample(
        x: Float,
        channel: Int,
        bits: Int,
        drive: Float,
        addNoise: Boolean,
    ): Float {
        val ch = channel.coerceIn(0, heldSample.lastIndex)
        val f = filters[channel.coerceIn(0, filters.lastIndex)]

        // 1. High-pass: trim sub-bass before it can waste quantisation steps.
        var y = f.highPass.process(x)

        // 2. Decimation: hold the sample for `decimate` consecutive samples.
        decimateCounter++
        if (decimateCounter >= decimate) {
            decimateCounter = 0
            heldSample[ch] = y
        }
        y = heldSample[ch]

        // 3. Bit depth reduction.
        y = quantise(y, bits)

        // 4. Warm saturation: soft clipper adds harmonics, the opposite
        //    of the bitcrusher's subtraction.
        y = saturate(y, drive)

        // 5. Low-pass: roll off the harshness the bitcrusher added.
        y = f.lowPass.process(y)

        // 6. Own noise texture (crackle + light hiss), only when vinyl noise
        //    is not sharing — added last, after every crush/filter stage
        //    above, so it is never quantised or decimated either. See
        //    TapRenderersFactory's class doc for why that ordering matters.
        if (addNoise) {
            y += noise.crackle(ch, active.intensity, sampleRate, amplitude = LoFiProcessor::loFiCrackleAmplitude)
            y += noise.hiss(ch, active.intensity, amplitude = LoFiProcessor::loFiHissAmplitude)
        }

        return y
    }

    override fun onFlush() {
        decimateCounter = 0
        heldSample.fill(0f)
        for (f in filters) {
            f.highPass.reset()
            f.lowPass.reset()
        }
        noise.onFlush()
    }

    override fun onReset() {
        // `active` is deliberately left alone — see VinylNoiseProcessor.onReset()
        // for the full reasoning. In short: by the time reset() reaches this
        // processor, `pending` has already been drained into `active`, and the
        // deduped settings Flow that refills `pending` (AppSettings.pref()) will
        // not re-emit unless the user actually changes the mode. Clearing `active`
        // here would switch lo-fi off for the rest of the session with nothing
        // left to switch it back on, rather than just for the buffer being reset.
        // `heldSample`, `filters` and `noise` are genuinely derived, not config —
        // sized to whatever channel count the old format needed — so they still
        // shrink back here, the same way LocalDsp.onReset() clears `sections`;
        // the next onConfigure() regrows them if the new format needs more channels.
        heldSample = FloatArray(2)
        filters = Array(2) { ChannelFilters() }
        noise.onReset()
    }
}
